### ISSUE TITLE
mac 系统，最新版本的操作系统，普通用户

### ISSUE THREAD

**Issue by hktalent** [keenwon/antcolony#19]
mac 系统，最新版本的操作系统，普通用户
npm install pm2@0.10.7 --save -g
报错

> pm2@0.10.7 preinstall /usr/local/lib/node_modules/.staging/pm2-d445599b
> bash ./scripts/preinstall.sh

/usr/local/bin/pm2 -> /usr/local/lib/node_modules/pm2/bin/pm2

> fsevents@0.2.0 install /usr/local/lib/node_modules/pm2/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../../nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))

```
                                 ~~~~~~~~~~~~^
```

../../nan/nan.h:343:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../../nan/nan.h:343:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))

```
                                 ~~~~~~~~~~~~^
```

../../nan/nan.h:348:9: error: no type named 'ThrowException' in namespace 'v8'
    v8::ThrowException(error);
    ~~~~^
../../nan/nan.h:355:65: error: no member named 'New' in 'v8::String'
    v8::Localv8::Value err = v8::Exception::Error(v8::String::New(msg));
                                                    ~~~~~~~~~~~~^
../../nan/nan.h:357:26: error: no member named 'New' in 'v8::String'
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
             ~~~~~~~~~~~~^
../../nan/nan.h:369:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::TypeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))

```
                                 ~~~~~~~~~~~~^
```

../../nan/nan.h:373:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../../nan/nan.h:373:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))

```
                                 ~~~~~~~~~~~~^
```

../../nan/nan.h:377:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::RangeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))

```
                                 ~~~~~~~~~~~~^
```

../../nan/nan.h:381:5: error: no member named 'ThrowException' in namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../../nan/nan.h:381:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))

```
                                 ~~~~~~~~~~~~^
```

../../nan/nan.h:406:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:141:71: note: expanded from macro 'NAN_INLINE'
# define NAN_INLINE(declarator) inline **attribute**((always_inline)) declarator

```
                                                                  ^
```

../../nan/nan.h:416:12: error: no matching function for call to 'New'
    return node::Buffer::New(data, size);
           ^~~~~~~~~~~~~~~~~
/Users/xiatian/.node-gyp/6.2.2/include/node/node_buffer.h:31:40: note: 
      candidate function not viable: no known conversion from 'char _' to
      'v8::Isolate *' for 1st argument
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate, size_t length);
                                       ^
/Users/xiatian/.node-gyp/6.2.2/include/node/node_buffer.h:34:40: note: 
      candidate function not viable: no known conversion from 'char _' to
      'v8::Isolate *' for 1st argument
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                       ^
/Users/xiatian/.node-gyp/6.2.2/include/node/node_buffer.h:39:40: note: 
      candidate function not viable: requires 5 arguments, but 2 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
/Users/xiatian/.node-gyp/6.2.2/include/node/node_buffer.h:46:40: note: 
      candidate function not viable: requires 3 arguments, but 2 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:420:12: error: no matching function for call to 'New'
    return node::Buffer::New(size);
           ^~~~~~~~~~~~~~~~~
/Users/xiatian/.node-gyp/6.2.2/include/node/node_buffer.h:31:40: note: 
      candidate function not viable: requires 2 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate, size_t length);
                                       ^
/Users/xiatian/.node-gyp/6.2.2/include/node/node_buffer.h:34:40: note: 
      candidate function not viable: requires at least 2 arguments, but 1 was
      provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
/Users/xiatian/.node-gyp/6.2.2/include/node/node_buffer.h:39:40: note: 
      candidate function not viable: requires 5 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
/Users/xiatian/.node-gyp/6.2.2/include/node/node_buffer.h:46:40: note: 
      candidate function not viable: requires 3 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:427:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(data, size);
           ~~~~~~~~~~~~~~^
../../nan/nan.h:727:49: error: too few arguments to function call, single
      argument 'isolate' was not specified
    v8::Localv8::Object obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
/Users/xiatian/.node-gyp/6.2.2/include/node/v8.h:2986:3: note: 'New' declared
      here
  static Local<Object> New(Isolate\* isolate);
  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:733:49: error: too few arguments to function call, single
      argument 'isolate' was not specified
    v8::Localv8::Object obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
/Users/xiatian/.node-gyp/6.2.2/include/node/v8.h:2986:3: note: 'New' declared
      here
  static Local<Object> New(Isolate\* isolate);
  ^
In file included from ../fsevents.cc:6:
../../nan/nan.h:740:12: error: no member named 'Dispose' in
      'v8::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    handle.Dispose();
    ~~~~~~ ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: **\* [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pm2/node_modules/fsevents
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:fsevents@0.2.0 fsevents@0.2.0 install: `node-gyp rebuild`
npm WARN install:fsevents@0.2.0 Exit status 1

> pm2@0.10.7 postinstall /usr/local/lib/node_modules/pm2
> bash ./scripts/postinstall.sh

**Comment by hktalent** [comment]
很奇怪，pm安装报错
mkdir ~/.pm2
后，但是可以用
pm2 start src/queen.js -f --name worker[3000] -- worker 3000
pm2 start src/queen.js -f --name worker[3001] -- worker 3001
pm2 start src/queen.js -f --name male[1] -- male 1
pm2 start src/queen.js -f --name female[1] -- female 1
运行，表面上没有错误，是正常的

**Comment by keenwon** [comment]
看样子是`fsevents`编译的时候报错，这个可能的原因很多，可能和版本有关，建议你还是搜索一下吧，我没遇到这个问题，给不了太多帮助。
