### ISSUE TITLE
Error: Expect "max_memory_restart" 

### ISSUE THREAD

**Issue by landolphin** [keenwon/antcolony#22]
`$ node startup worker 3000
Error: Expect "max_memory_restart" to be a typeof [object String] / [object Numb
er], but now is [object Object]
    at Object.Common.verifyConfs (D:\nodejs\ss\antcolony\node_modules\_pm2@2.10.
1@pm2\lib\Common.js:624:14)
    at module.exports.API._startScript (D:\nodejs\ss\antcolony\node_modules\_pm2
@2.10.1@pm2\lib\API.js:692:25)
    at module.exports.API.start (D:\nodejs\ss\antcolony\node_modules\_pm2@2.10.1
@pm2\lib\API.js:325:10)
    at D:\nodejs\ss\antcolony\startup:20:13
    at D:\nodejs\ss\antcolony\node_modules\_pm2@2.10.1@pm2\lib\API.js:169:14
    at D:\nodejs\ss\antcolony\node_modules\_pm2@2.10.1@pm2\lib\Client.js:54:16
    at Timeout._onTimeout (D:\nodejs\ss\antcolony\node_modules\_pm2@2.10.1@pm2\l
ib\Client.js:360:19)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
`

请问这是什么错误哈？

**Comment by keenwon** [comment]
使用 pm2@0.10.7 试试

**Comment by tineroll** [comment]
pm2 版本的问题windows 下有此问题，换 linux 就好了。
也可以注释掉 startup 里面的 maxMemoryRestart: config.memoryLimit 解决。
